name: Version release
on:
  pull_request_target: 
    branches:
      - master
    types:
      - closed

jobs:
  if_merged:
     if: github.event.pull_request.merged == true
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
              
      - name: git config
        run: |
          git config user.name "Speedwares"
          git config user.email "ovuobasampson@gmail.com"
        
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
   
      - name: Install dependencies (Clean install)
        run: npm ci --legacy-peer-deps
        
      - name: Run release command
        run: npm run release
        
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
